---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: no
configure_terminal: no
configure_osx: no

dotfiles_repo: ssh://git@github.com/jrgoldfinemiddleton/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Developer/dotfiles
dotfiles_files:
  - .bash_aliases
  - .bash_profile
  - .bashrc
  - .gitconfig
  - .tmux.conf
  - .vimrc
#  - .osx

homebrew_installed_packages:
  - ansible
  - bash-completion
  - git
  - htop
  - iperf
  - nmap
  - openssl
  - vagrant-completion
  - wget

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - firefox
  - macvim
  - sequel-pro
  - vagrant
  - virtualbox
  - virtualbox-extension-pack

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

# See `jrgoldfinemiddleton.vim` role documentation for usage instructions.
vim_install_autoload_scripts:
  - filename: pathogen.vim
    url: https://tpo.pe/pathogen.vim

vim_install_plugins:
  - name: vim-sensible
    repo: https://github.com/tpope/vim-sensible.git
  - name: ansible-vim
    repo: https://github.com/pearofducks/ansible-vim.git

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
